use_frameworks!

target 'SitataCore_Example' do
  pod 'SitataCore', :path => '../'

  target 'SitataCore_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
